# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  # - name: Bio
  #   url: /
  #   weight: 10
  # - name: Talks
  #   url: /#talks
  #   weight: 12
  - name: CV
    # url: /experience/
    url: /cv/
    weight: 20
  - name: Publications
    url: /publications/
    weight: 25
  - name: Data
    url: /datasets/
    weight: 35
  - name: Teaching
    url: /teaching/
    weight: 40
  # - name: Courses
  #   url: courses/
  #   weight: 40
